# Generated by Django 2.2.12 on 2020-04-10 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0024_auto_20200401_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='map',
        ),
        migrations.RemoveField(
            model_name='project',
            name='timeseries',
        ),
        migrations.DeleteModel(
            name='Mirror',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Timeseries',
        ),
    ]
