# Generated by Django 2.2.12 on 2020-04-10 10:33

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('ogc', '0002_data_20200410_0930'),
        ('maps', '0025_auto_20200410_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='ogc_layer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ogc.Layer'),
        ),
    ]
