# Generated by Django 2.2.12 on 2020-04-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0026a_copy_layers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layer',
            old_name='layer',
            new_name='wms_layer',
        ),
        migrations.RenameField(
            model_name='layer',
            old_name='ogc_layer',
            new_name='layer',
        ),
    ]
