# Generated by Django 2.2.12 on 2020-04-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0027_auto_20200410_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='wms_layer',
        ),
    ]
