# Generated by Django 2.2.12 on 2020-04-13 09:29

from django.db import migrations

def set_layer_group(apps, schema_editor):
    ''' set default layer groups '''
    overlay = ['density','proximity','lithology','recharge','slope','landuse','suitability']
    Map = apps.get_model('maps', 'Map')
    for m in Map.objects.all():
        group, _created = m.group_set.get_or_create(name='Overlay')
        m.layer_set.filter(group__isnull=True,layer__title__in=overlay).update(group=group)
        group, _created = m.group_set.get_or_create(name='Layers')
        m.layer_set.filter(group__isnull=True).update(group=group)

def undo(apps, schema_editor):
    ''' undo set default layer group '''
    Map = apps.get_model('maps', 'Map')
    for m in Map.objects.all():
        m.layer_set.filter(group__name__in=['Layers','Overlay']).update(group=None)

class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0029_auto_20200413_0903'),
    ]

    operations = [
        migrations.RunPython(set_layer_group, undo)
    ]
