# Generated by Django 2.2.12 on 2020-04-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0031_map_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='slug',
        ),
        migrations.AlterField(
            model_name='map',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
