# Generated by Django 2.2.12 on 2020-04-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0032_auto_20200414_0925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserConfig',
        ),
    ]
