# Generated by Django 2.2.12 on 2020-08-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0036_auto_20200730_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
