version: '3'
services:
    db:
      image: postgres
      env_file: pg.env
      volumes:
        - ./pgdata:/var/lib/postgresql/data
        - ./initdb.d:/docker-entrypoint-initdb.d

    gw4e:
      build: .
      env_file: django.env
      volumes:
        - .:/code
      command: gunicorn -w 4 -b 0.0.0.0:8000 maps.wsgi
      ports:
        - "8000:8000"
      depends_on:
        - db

