# Generated by Django 2.2.12 on 2020-04-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('url', models.URLField(max_length=255, verbose_name='url')),
                ('service_type', models.CharField(choices=[('WMS', 'WMS'), ('WFS', 'WFS')], default='WMS', max_length=4, verbose_name='type')),
                ('version', models.CharField(choices=[('WMS', (('1.1.1', '1.1.1'), ('1.3.0', '1.3.0'))), ('WFS', (('1.0.0', '1.0.0'), ('1.1.0', '1.1.0'), ('2.0.0', '2.0.0'), ('3.0.0', '3.0.0')))], default='1.3.0', max_length=10, verbose_name='version')),
            ],
            options={
                'verbose_name': 'Server',
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layername', models.CharField(max_length=100, verbose_name='layername')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('bbox', models.CharField(blank=True, max_length=100, null=True, verbose_name='extent')),
                ('attribution', models.CharField(blank=True, max_length=200, null=True, verbose_name='attribution')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ogc.Server', verbose_name='WMS Server')),
            ],
            options={
                'verbose_name': 'Layer',
            },
        ),
    ]
