# Generated by Django 2.2.12 on 2020-04-10 09:30

from django.db import migrations

def migrate_to_ows(apps, schema_editor):
    ''' copy wms and wfs layers to ogc app '''
    OGCServer = apps.get_model('ogc', 'Server')
    for service_type in ['WMS', 'WFS']:
        app_name = service_type.lower()
        Server = apps.get_model(app_name, 'Server')
        for s in Server.objects.all():
            server = OGCServer.objects.create(name=s.name, url=s.url, version=s.version, service_type=service_type)
            for l in s.layer_set.all():
                attribution = l.attribution if hasattr(l,'attribution') else ''
                server.layer_set.create(layername=l.layername, title=l.title, bbox = l.bbox, attribution = attribution)

def reverse(apps, schema_editor):
    OGCServer = apps.get_model('ogc', 'Server')
    for s in OGCServer.objects.all():
        app_name = s.service_type.lower()
        Server = apps.get_model(app_name, 'Server')
        server = Server.objects.create(name=s.name, url=s.url, version=s.version, service_type=s.service_type)
        for l in s.layer_set.all():
            server.layer_set.create(layername=l.layername, title=l.title, bbox = l.bbox, attribution = l.attribution)

def fake_reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('ogc', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_to_ows, fake_reverse)
    ]
