# Generated by Django 2.2.12 on 2020-04-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogc', '0002_data_20200410_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='legend',
            field=models.URLField(blank=True, null=True, verbose_name='legend_url'),
        ),
        migrations.AddField(
            model_name='layer',
            name='tiled',
            field=models.BooleanField(default=True, verbose_name='tiled'),
        ),
    ]
