# Generated by Django 2.2.12 on 2020-04-10 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ogc', '0003_auto_20200410_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=30, verbose_name='property')),
                ('title', models.CharField(default='legend', max_length=40, verbose_name='title')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legends', to='ogc.Layer')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('label', models.CharField(blank=True, max_length=40, null=True)),
                ('value', models.CharField(max_length=40)),
                ('legend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ogc.Legend')),
            ],
            options={
                'ordering': ('value',),
            },
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('label', models.CharField(blank=True, max_length=40, null=True)),
                ('lo', models.FloatField()),
                ('hi', models.FloatField()),
                ('legend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ogc.Legend')),
            ],
            options={
                'ordering': ('lo', 'hi'),
            },
        ),
    ]
