# Generated by Django 2.2.12 on 2020-04-13 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ogc', '0004_legend_range_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legend',
            name='layer',
            field=models.ForeignKey(limit_choices_to={'server__service_type': 'WFS'}, on_delete=django.db.models.deletion.CASCADE, related_name='legends', to='ogc.Layer'),
        ),
    ]
