# Generated by Django 2.2.12 on 2020-05-04 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Layer',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
