# Generated by Django 2.2.12 on 2020-04-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0005_auto_20190905_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='legend',
            field=models.URLField(blank=True, null=True, verbose_name='legend_url'),
        ),
    ]
