# Generated by Django 2.2.12 on 2020-04-08 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={'verbose_name': 'WFS-Layer'},
        ),
        migrations.RemoveField(
            model_name='layer',
            name='attribution',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='tiled',
        ),
    ]
